=== JamboToYou/oop/Practics_5/Practics_5/Contacts.xsd
<?xml version="1.0" encoding="utf-8"?><xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="contacts">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="contact">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="FirstName" type="xs:string" />
              <xs:element name="SecondName" type="xs:string" />
              <xs:element name="Number" type="xs:unsignedLong" />
              <xs:element name="EMail" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="Id" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JamboToYou/oop/Practics_5/Practics_5/bin/Debug/Contacts.xml
<?xml version="1.0" encoding="utf-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://msiter.ru Contacts.xsd">
  <contact Id="0">
    <FirstName>Vlad</FirstName>
    <SecondName>Lee</SecondName>
    <Number>j89011234567</Number>
    <EMail>vlad.lee@mail.ru</EMail>
  </contact>
  <contact Id="1">
    <FirstName>Andrey</FirstName>
    <SecondName>Tyu</SecondName>
    <Number>89020458673</Number>
    <EMail>jambotoyou@gmail.com</EMail>
  </contact>
  <contact Id="2">
    <FirstName>ndre</FirstName>
    <SecondName>g</SecondName>
    <Number>345532345</Number>
    <EMail />
  </contact>
  <contact Id="3">
    <FirstName>ert</FirstName>
    <SecondName>dr</SecondName>
    <Number>34523</Number>
    <EMail />
  </contact>
  <contact Id="5">
    <FirstName>Daniil</FirstName>
    <SecondName>Khudorozkhov</SecondName>
    <Number>43563653</Number>
    <EMail>dfghdfgh</EMail>
  </contact>
</contacts>

=== JamboToYou/oop/Practics_5/Practics_5/Contacts.xml
<?xml version="1.0" encoding="utf-8" ?>
<contacts xmlns="http://msiter.ru"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://msiter.ru Contacts.xsd">
  <contact Id="0">
    <FirstName>Vlad</FirstName>
    <SecondName>Lee</SecondName>
    <Number>89011234567</Number>
    <EMail>vlad.lee@mail.ru</EMail>
  </contact>
  <contact Id="1">
    <FirstName>Andrey</FirstName>
    <SecondName>Tyu</SecondName>
    <Number>89020458673</Number>
    <EMail>jambotoyou@gmail.com</EMail>
  </contact>
</contacts>
