<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE CONTACT_NOTES [
  <!ELEMENT CONTACT_NOTES (CONTACT)*>
  <!ELEMENT CONTACT (FIRST_NAME, LAST_NAME, NUMBER, EMAIL)>
  <!ATTLIST CONTACT ID CDATA #REQUIRED>
  <!ELEMENT FIRST_NAME (#PCDATA)>
  <!ELEMENT LAST_NAME (#PCDATA)>
  <!ELEMENT NUMBER (#PCDATA)>
  <!ELEMENT EMAIL (#PCDATA)>
]>

<CONTACT_NOTES>
  <CONTACT ID="1232">
    <FIRST_NAME>gdfgf</FIRST_NAME>
    <LAST_NAME>dthfghr</LAST_NAME>
    <NUMBER>gdhg</NUMBER>
    <EMAIL>fdghdgh</EMAIL>
  </CONTACT>
</CONTACT_NOTES>